use std::env;
use std::fs;
use std::path::Path;

fn get_float(value: &toml::Value, key: &str) -> f32 {
    value.as_float().map(|f| f as f32)
        .or_else(|| value.as_integer().map(|i| i as f32))
        .unwrap_or_else(|| panic!("Missing or invalid {}", key))
}

fn main() {
    // Read the shared constants file
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    
    // Try parent directory first (normal workspace), then current directory (Docker build)
    let constants_path = Path::new(&manifest_dir).parent().unwrap().join("game-constants.toml");
    let constants_path = if constants_path.exists() {
        constants_path
    } else {
        Path::new(&manifest_dir).join("game-constants.toml")
    };
    
    // Tell Cargo to rerun this build script if the constants file changes
    println!("cargo:rerun-if-changed={}", constants_path.display());
    
    // Parse the TOML file
    let contents = fs::read_to_string(&constants_path)
        .expect("Failed to read game-constants.toml");
    let config: toml::Value = toml::from_str(&contents)
        .expect("Failed to parse game-constants.toml");
    
    // Extract values
    let physics = config.get("physics").expect("Missing [physics] section");
    let gameplay = config.get("gameplay").expect("Missing [gameplay] section");
    
    let thrust_accel = get_float(physics.get("thrust_accel").unwrap(), "thrust_accel");
    let rotation_speed = get_float(physics.get("rotation_speed").unwrap(), "rotation_speed");
    let max_speed = get_float(physics.get("max_speed").unwrap(), "max_speed");
    let drag = get_float(physics.get("drag").unwrap(), "drag");
    let world_limit = get_float(physics.get("world_limit").unwrap(), "world_limit");
    let ship_radius = get_float(gameplay.get("ship_radius").unwrap(), "ship_radius");
    let invincibility_duration = get_float(gameplay.get("invincibility_duration").unwrap(), "invincibility_duration");
    
    // Generate the constants.rs file
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_constants.rs");
    
    let generated_code = format!(
        r#"// This file is auto-generated by build.rs from game-constants.toml
// DO NOT EDIT MANUALLY - your changes will be overwritten

pub const THRUST_ACCEL: f32 = {:.1};  // pixels/sec²
pub const ROTATION_SPEED: f32 = {:.1};   // radians/sec
pub const MAX_SPEED: f32 = {:.1};     // pixels/sec
pub const DRAG: f32 = {};            // velocity multiplier per frame
pub const SHIP_RADIUS: f32 = {:.1};     // pixels
pub const WORLD_LIMIT: f32 = {:.1};    // world boundary for wrapping
pub const INVINCIBILITY_DURATION: f32 = {:.1};  // seconds after respawn
"#,
        thrust_accel,
        rotation_speed,
        max_speed,
        drag,
        ship_radius,
        world_limit,
        invincibility_duration,
    );
    
    fs::write(&dest_path, generated_code)
        .expect("Failed to write generated_constants.rs");
}
