// Physics constants for the game
// These are auto-generated from game-constants.toml at build time
// DO NOT EDIT THIS FILE - edit game-constants.toml instead

include!(concat!(env!("OUT_DIR"), "/generated_constants.rs"));
